// Code generated by "stringer -type voteValueType"; DO NOT EDIT.

package vpack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[credPfVoteValue-0]
	_ = x[rPerVoteValue-1]
	_ = x[rPropDigVoteValue-2]
	_ = x[rPropEncdigVoteValue-3]
	_ = x[rPropOperVoteValue-4]
	_ = x[rPropOpropVoteValue-5]
	_ = x[rRndVoteValue-6]
	_ = x[rSndVoteValue-7]
	_ = x[rStepVoteValue-8]
	_ = x[sigP1sVoteValue-9]
	_ = x[sigP2VoteValue-10]
	_ = x[sigP2sVoteValue-11]
	_ = x[sigPVoteValue-12]
	_ = x[sigPsVoteValue-13]
	_ = x[sigSVoteValue-14]
}

const _voteValueType_name = "credPfVoteValuerPerVoteValuerPropDigVoteValuerPropEncdigVoteValuerPropOperVoteValuerPropOpropVoteValuerRndVoteValuerSndVoteValuerStepVoteValuesigP1sVoteValuesigP2VoteValuesigP2sVoteValuesigPVoteValuesigPsVoteValuesigSVoteValue"

var _voteValueType_index = [...]uint8{0, 15, 28, 45, 65, 83, 102, 115, 128, 142, 157, 171, 186, 199, 213, 226}

func (i voteValueType) String() string {
	if i >= voteValueType(len(_voteValueType_index)-1) {
		return "voteValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _voteValueType_name[_voteValueType_index[i]:_voteValueType_index[i+1]]
}
